<h2>Editar Tarea</h2>

<div class="container">
    <div class="col-md-12">
        <form action="<?php echo APP_URL.'categorias/editar'; ?>" method="POST">
            <input type="hidden" value="<?php echo $this->categoria['id']; ?>" name="id">
            <label for="nombre">Nombre</label>
            <div class="input-group">           
                <input type="text" name="nombre" class="form-control" value="<?php echo $this->categoria['nombre']; ?>">
                <div class="input-group-append">
                    <button class="btn btn-sm btn-success" action="submit">Editar</button>
                </div>
            </div>
        </form>
    </div>
</div>